version: '3.8'

services:
  virtual-ocpp-j-ui:
    container_name: virtual-ocpp-j-ui
    build:
      context: ./
      target: base
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - .:/app
    command: 'npm run start'
    stdin_open: true
